# Generated by Django 5.1.7 on 2025-03-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nombreUsuario',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
