# Generated by Django 5.1.7 on 2025-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_usuarios_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarios',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chalecos',
            name='serial',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
